version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=souaad
      - POSTGRES_DB=postgres_db
